#Bibek Shiwakoti
'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

'''



#solution approach
'for this nature of the problem we can find the sum of the ASCII of characters in both \
 and substract from high to low to find the character added ord function gives the ASCII and chr function ' \
'returns the character corresponding to the value'


class Solution(object):
    def findTheDifference(self, s, t):
        sum_t = sum(ord(char) for char in t)
        sum_s = sum(ord(char) for char in s)

        return chr(sum_t - sum_s)


obj = Solution()
s='apple'
t='apple2'
print(obj.findTheDifference(s,t))


s1=''
t1='w'
print(obj.findTheDifference(s1,t1))




